In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [12]:
data_url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, names=['CRIM','ZN','INDUS','CHAS','NOX','RM','AGE','DIS','RAD','TAX','PTRATIO','B','LSTAT','MEDV']
data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
target = raw_df.values[1::2, 2]

SyntaxError: invalid syntax (2038325341.py, line 3)

In [13]:
raw_df

0      1      2    3      4      5     6       7    8      9   \
0       0.00632  18.00   2.31  0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1     396.90000   4.98  24.00  NaN    NaN    NaN   NaN     NaN  NaN    NaN   
2       0.02731   0.00   7.07  0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
3     396.90000   9.14  21.60  NaN    NaN    NaN   NaN     NaN  NaN    NaN   
4       0.02729   0.00   7.07  0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
...         ...    ...    ...  ...    ...    ...   ...     ...  ...    ...   
1007  396.90000   5.64  23.90  NaN    NaN    NaN   NaN     NaN  NaN    NaN   
1008    0.10959   0.00  11.93  0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
1009  393.45000   6.48  22.00  NaN    NaN    NaN   NaN     NaN  NaN    NaN   
1010    0.04741   0.00  11.93  0.0  0.573  6.030  80.8  2.5050  1.0  273.0   
1011  396.90000   7.88  11.90  NaN    NaN    NaN   NaN     NaN  NaN    NaN   

        10  
0     15.3  
1      NaN  
2     17.8  
3      NaN  
4     17.8  
...    ...  
1007   NaN  
1008  21.0  
1009   NaN  
1010  21.0  
1011   NaN  

[1012 rows x 11 columns]

In [7]:
!pip install scikit-learn==1.1.3

Defaulting to user installation because normal site-packages is not writeable
                                              0.0/7.5 MB ? eta -:--:--
                                              0.0/7.5 MB ? eta -:--:--
                                              0.0/7.5 MB ? eta -:--:--
                                              0.0/7.5 MB ? eta -:--:--
                                              0.0/7.5 MB ? eta -:--:--
                                              0.0/7.5 MB ? eta -:--:--
                                              0.0/7.5 MB ? eta -:--:--
                                              0.0/7.5 MB ? eta -:--:--
                                              0.0/7.5 MB ? eta -:--:--
                                              0.1/7.5 MB 326.1 kB/s eta 0:00:23
                                              0.1/7.5 MB 326.1 kB/s eta 0:00:23
                                              0.1/7.5 MB 326.1 kB/s eta 0:00:23
                                           

In [16]:
df = pd.read_csv('Boston.csv', index_col=0)

In [20]:

df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 506 entries, 1 to 506
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   crim     506 non-null    float64
 1   zn       506 non-null    float64
 2   indus    506 non-null    float64
 3   chas     506 non-null    int64  
 4   nox      506 non-null    float64
 5   rm       506 non-null    float64
 6   age      506 non-null    float64
 7   dis      506 non-null    float64
 8   rad      506 non-null    int64  
 9   tax      506 non-null    int64  
 10  ptratio  506 non-null    float64
 11  black    506 non-null    float64
 12  lstat    506 non-null    float64
 13  medv     506 non-null    float64
dtypes: float64(11), int64(3)
memory usage: 59.3 KB


In [21]:
df

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  \
1    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
2    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
3    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242   
4    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
5    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
502  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273   
503  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
504  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
505  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273   
506  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   

     ptratio   black  lstat  medv  
1       15.3  396.90   4.98  24.0  
2       17.8  396.90   9.14  21.6  
3       17.8  392.83   4.03  34.7  
4       18.7  394.63   2.94  33.4  
5       18.7  396.90   5.33  36.2  
..       ...     ...    ...   ...  
502     21.0  391.99   9.67  22.4  
503     21.0  396.90   9.08  20.6  
504     21.0  396.90   5.64  23.9  
505     21.0  393.45   6.48  22.0  
506     21.0  396.90   7.88  11.9  

[506 rows x 14 columns]

In [23]:
np.sum(df.isnull())

crim       0
zn         0
indus      0
chas       0
nox        0
rm         0
age        0
dis        0
rad        0
tax        0
ptratio    0
black      0
lstat      0
medv       0
dtype: int64

In [26]:
df.corr()['medv'].sort_values()

lstat     -0.737663
ptratio   -0.507787
indus     -0.483725
tax       -0.468536
nox       -0.427321
crim      -0.388305
rad       -0.381626
age       -0.376955
chas       0.175260
dis        0.249929
black      0.333461
zn         0.360445
rm         0.695360
medv       1.000000
Name: medv, dtype: float64

In [46]:
X= df.drop('medv', axis=1)

In [28]:
X

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  \
1    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
2    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
3    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242   
4    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
5    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
502  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273   
503  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
504  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
505  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273   
506  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   

     ptratio   black  lstat  
1       15.3  396.90   4.98  
2       17.8  396.90   9.14  
3       17.8  392.83   4.03  
4       18.7  394.63   2.94  
5       18.7  396.90   5.33  
..       ...     ...    ...  
502     21.0  391.99   9.67  
503     21.0  396.90   9.08  
504     21.0  396.90   5.64  
505     21.0  393.45   6.48  
506     21.0  396.90   7.88  

[506 rows x 13 columns]

In [47]:
y = df['medv']

In [48]:
from sklearn.model_selection import train_test_split

In [49]:
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.3)

In [50]:
from sklearn.preprocessing import StandardScaler

In [51]:
scaler = StandardScaler()

In [52]:
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [53]:
from sklearn.linear_model import LinearRegression

In [54]:
model = LinearRegression()

In [55]:
model.fit(X_train,y_train)

LinearRegression()

In [56]:
prediction=model.predict(X_test)

In [57]:
prediction

array([ 6.83506343, 15.80876409, 16.53932303, 23.15656126, 28.34259524,
       15.49510221, 23.50134188, 10.10324829, 30.83613009, 20.3346384 ,
       13.31115697, 37.25353025, 18.54186935,  6.65990673, 33.46094112,
        5.34883376, 25.2831487 , 19.35658289, 23.62117812, 27.57665865,
       35.78929028, 32.18296941, 17.65221756, 25.54779785, 22.33289199,
       21.27623942, 39.83626609, 24.67118941,  6.8485925 , 36.56894753,
       23.68238979, 34.00953211, 27.52869022, 10.26853121, 10.65082187,
       29.50863486, 39.50007277, 20.14849764, 32.84877419, 23.23984269,
       26.1148747 , 12.28954395, 20.05887476, 19.25509067, 18.01612204,
       27.231659  , 17.67320499, 11.86206903, 13.37908793, 17.78184278,
       16.94689571, 18.36361553, 13.92719153, 15.46898966, 19.130535  ,
       19.86499798, 27.07833491, 28.05666122, 11.67132852, 18.26579118,
       32.15668705, 21.22263365, 23.44573311, -0.07572192, 13.28666767,
       12.45838248,  8.90393245, 20.5011216 , 22.26228691, 21.06

In [58]:
model.coef_

array([-1.06292774,  1.33900473,  0.18680977,  0.99428805, -2.33162848,
        2.64872852, -0.33268915, -3.34762124,  2.26473733, -2.00535942,
       -1.73956626,  0.54086392, -3.44242926])

In [59]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [61]:
print(mean_absolute_error(y_test,prediction))

3.6417930415947914


In [62]:
print(mean_squared_error(y_test,prediction))

25.801727626814973


In [63]:
print(np.sqrt(mean_squared_error(y_test,prediction)))

5.079540099931782


In [72]:
df1 = df.drop('medv', axis=1).to_numpy()

In [88]:
A=df1[0].reshape(1,-1)

In [89]:
scaler.transform(A)

C:\Users\User\anaconda3\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[-0.40049304,  0.23063646, -1.2780555 , -0.26360274, -0.12456762,
         0.38340352, -0.06493899,  0.1273586 , -0.97524926, -0.66980818,
        -1.47230989,  0.43690592, -1.07310377]])

In [90]:
model.predict(scaler.transform(A))

C:\Users\User\anaconda3\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([29.35930044])

In [91]:
import pickle

In [85]:
pickle.dump(model,open('regmodel1.pkl','wb'))

In [86]:
pickled_model = pickle.load(open('regmodel1.pkl','rb'))

In [92]:
pickled_model.predict(scaler.transform(A))

C:\Users\User\anaconda3\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([29.35930044])